### ISSUE TITLE
Storing data in Dat

### ISSUE THREAD

**Issue by ninabreznik** [blockscout/etherscan-scraper#40]
We need to refactor scraper to store directly on DAT

Possible flow:

* every new source code is new dat
* all dats use mount so we have a registry of all source codes that we will scrape

**Comment by ninabreznik** [comment]
@RangerMauve, @alincode, @karissa @serapath
I moved issues here and will close the repo under my Github account.

**Comment by karissa** [comment]
Hi, yes I think this is a good first step, although it might not require a refactor persay. I'd rename this issue to 'Storing data in Dat'

It is essentially a bunch of data (now stored in MySQL) that *can be* represented on the filesystem, but currently is not. Concrete changes to make:

1) Existing script should output also files to a filesystem
2) Each repository is a Dat 
3) There is a global etherscan Dat that mounts all these sub-repos 
4) This dat is hosted somewhere, perhaps using Dat-store?
